{{- if .Values.metalLB.enable | default true }}
{{- range .Values.metalLB.servers }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-{{ .name }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb/'
    targetRevision: {{ .Values.metalLB.version }}
    chart: 'metallb'
    directory:
      recurse: false
  sources: []
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}      