apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
data:
  GF_AUTH_ANONYMOUS_ORG_ROLE: {{ .Values.env.gfAuthAnonymousOrgRole | b64enc | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.env.gfSecurityAdminPassword | b64enc | quote }}