---
# Source: Helm cluster addons/templates/cert-manager.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: cert-manager-mlt-demo
  name: cert-manager-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.13.3
    chart: cert-manager
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/external-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: external-secrets-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.13
    chart: 'external-secrets'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        null
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/kubeclarity.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clarity-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubeclarity-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://openclarity.github.io/kubeclarity'
    targetRevision: v2.23.1
    chart: 'kubeclarity'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        kubeclarity:
          ingress:
            enabled: false
            ingressClassName: nginx
          service:
            type: LoadBalancer
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/longhorn.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.6.0
    chart: 'longhorn'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          enabled: false
        preUpgradeChecker:
          jobEnabled: false
          upgradeVersionCheck: false
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-demo
#  name: metallb-waj-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb/'
    targetRevision: 0.13.12
    chart: 'metallb'
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: ext-metallb-epz-demo
  name: ext-metallb-demo
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/extras/metallb'
    targetRevision: main
  destination:
    namespace: metallb-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metric-server.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.9.3
    chart: metrics-server
    helm:
      valueFiles:
        - values.yaml
      values: |
        apiService:
          create: true
        extraArgs:
          - --kubelet-insecure-tls=true
          - --kubelet-preferred-address-types=InternalIP

  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/prometheus.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-demo
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/monitoring/prometheus'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          className: nginx
          enabled: false
          environment: edge
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.11.29.201
          type: LoadBalancer
  destination:
    namespace: prometheus-system
    server: https://internal-edge-clusters-demo-apiserver-194354061.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
