
{{- if .Values.certManager.enable | default true }}
{{- range .Values.certManager.servers }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-{{ .name }}
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: {{ .Values.certManager.version }}
    chart: cert-manager
    directory:
      recurse: false
  sources: []
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}