{{- $externalSecret := .Values.externalSecret | default dict }}
{{- if $externalSecret.enable | default false }}
{{- range $externalSecret.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "secret-%s" .name | trunc 15 }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: external-secrets-system
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: {{ $externalSecret.version }}
    chart: 'external-secrets'
    helm:
      valueFiles:
        - values.yaml
      values: |
        {{ toYaml .values | nindent 8 }}
  sources: []
  project: {{ $.Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}