{{- $longhorn := .Values.longhorn | default dict }}
{{- if $longhorn.enable | default false }}
{{- range $longhorn.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "longhorn-%s" .name | trunc 50 }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: {{ $longhorn.version }}
    chart: 'longhorn'
    helm:
      valueFiles:
        - values.yaml
      values: |
        {{ toYaml .values | nindent 8 }}
        preUpgradeChecker:
          jobEnabled: false
          upgradeVersionCheck: false
  sources: []
  project: {{ $.Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}