{{- $awsLb := .Values.awsLb | default dict }}
{{- if $awsLb.enable | default false }}
{{- range $awsLb.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "ext-awsLb-%s" .name | trunc 50 }}
  namespace: argocd
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: 'https://github.com/andresanaya21/tactile5g-local-auto-ztp.git'
    path: 'templates/cluster-addons/extras/awsLb'
    targetRevision: main
  destination:
    server: {{ .url }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "awsLb-%s" .name | trunc 50 }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: awslb-system
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://aws.github.io/eks-charts'
    targetRevision: {{ $awsLb.version }}
    chart: 'awsLb'
    helm:
      valueFiles:
        - values.yaml
      values: |
        clusterName: {{ printf "%s" .name }}
  sources: []
  project: {{ $.Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}