{{- $certManager := .Values.certManager | default dict }}
{{- if $certManager.enable | default false }}
{{- range $certManager.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: {{ printf "cert-manager-%s-%s" (randAlpha 3 | lower) .name | trunc 30 }}
  name: {{ printf "cert-manager-%s" .name | trunc 50 }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: {{ $certManager.version }}
    chart: cert-manager
  project: {{ $.Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}
