{{- $kubeClarity := .Values.kubeClarity | default dict }}
{{- if $kubeClarity.enable | default false }}
{{- range $kubeClarity.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "clarity-%s" .name | trunc 25 }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubeclarity-system
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://openclarity.github.io/kubeclarity'
    targetRevision: {{ $kubeClarity.version }}
    chart: 'kubeclarity'
    helm:
      valueFiles:
        - values.yaml
      values: |
        {{ toYaml .values | nindent 8 }}
  sources: []
  project: {{ $.Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}