network:
  version: 2
  renderer: networkd
  ethernets:
    ens6:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
      routes:
        - to: 10.11.0.0/16
          via: 10.11.29.1
        - to: 10.182.32.0/24
          via: 10.11.29.1