{{- $metricServer := .Values.metricServer | default dict }}
{{- if $metricServer.enable | default false }}
{{- range $metricServer.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "metric-server-%s" .name | trunc 30 }}
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-system
    server: {{ .url }}
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: {{ $metricServer.version }}
    chart: metrics-server
    helm:
      valueFiles:
        - values.yaml
      values: |
        apiService:
          create: true
        extraArgs:
          - --kubelet-insecure-tls=true
          - --kubelet-preferred-address-types=InternalIP

  project: {{ $.Values.project }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
{{- end }}
{{- end }}