apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-clusters-digital-twins-0
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: digital-twins-0
    server: 'https://kubernetes.default.svc'
  sources:
    - path: sites/digital-twins-0/helm-edge-chart
      repoURL: 'https://github.com/andresanaya21/tactile5g-local-auto-ztp.git'
      targetRevision: main
      helm:
        valueFiles:
          - $values/digital-twins-0/edge/values.yaml
    - repoURL: 'https://github.com/andresanaya21/tactile5g-local-provisioning.git'
      targetRevision: 'dt/digital-twins-0'
      ref: values
  project: clusters
  syncPolicy:
    automated: {}
    #      prune: true
    #      allowEmpty: true
    #      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
#      - PruneLast=true
#      - PrunePropagationPolicy=background
