{{- if eq .Values.cluster.zone "edge" }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .name }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: {{ .name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
     # by default install k3s distribution
      name: null
      repo: null
      version: null
    values: |-
      service:
        type: LoadBalancer
      sync:
        persistentvolumeclaims:
          enabled: true
        ingresses:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        host: {{ .name }}.{{ .name }}
#  kubernetesVersion: {{ .Values.cluster.version }}
{{- end }}