---
# Source: region-clusters/templates/capi-template-aws.yaml
# this file install infra in aws (vpc, igw, natgwt, route-table)
# additionally ec2, lb, sgs
# install 1 master (control plane), 1 node (worker)
# https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/templates/cluster-template.yaml
# https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/templates/cluster-template-simple-clusterclass.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: region-clusters-example-region-0
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: region-clusters-example-region-0
  namespace: region-clusters-example-region-0
spec:
  region: eu-west-3
  additionalTags:
    enviroment: region
  controlPlaneLoadBalancer:
    scheme: internal
    subnets:
      - "default-subnet-1"  # default subnet
      - "default-subnet-2"  # default subnet
      - "default-subnet-3"  # default subnet
  sshKeyName: tactile5g
  bastion:
    enabled: false
  network:
    vpc:
      id: vpc-08291124993d8220b
    subnets:
      - id: default-subnet-1  # default subnet
      - id: default-subnet-2   # default subnet
      - id: "default-subnet-3"  # default subnet
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: "region-clusters-example-region-0-control-plane"
  namespace: region-clusters-example-region-0
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: tactile5g
      rootVolume:
        size: 80
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: "region-clusters-example-region-0-worker"
  namespace: region-clusters-example-region-0
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: tactile5g
      rootVolume:
        size: 80
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: region-clusters-example-region-0
  namespace: region-clusters-example-region-0
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: "region-clusters-example-region-0-control-plane"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: region-clusters-example-region-0
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "region-clusters-example-region-0-worker"
  namespace: region-clusters-example-region-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}'
      preKubeadmCommands:
        - |
          sudo echo "
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens6:
                dhcp4: true
                dhcp4-overrides:
                  use-routes: false
                routes:
                  - to: 10.11.0.0/16
                    via: 10.11.29.1
                  - to: 10.182.32.0/24
                    via: 10.11.29.1
          " | sudo tee -a /etc/netplan/ens6.yaml
      postKubeadmCommands:
        - netplan apply && ip link set ens6 up
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: "region-clusters-example-region-0-control-plane"
  namespace: region-clusters-example-region-0
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: "region-clusters-example-region-0-control-plane"
  replicas: 1
  version: v1.25.0
---
# Source: region-clusters/templates/capi-template-aws.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "region-clusters-example-region-0-worker"
  namespace: region-clusters-example-region-0
spec:
  clusterName: region-clusters-example-region-0
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: "region-clusters-example-region-0-worker"
      clusterName: region-clusters-example-region-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: "region-clusters-example-region-0-worker"
      version: v1.25.0
