---
# Source: Helm cluster addons/templates/aws-lb-controller.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ext-awslb-core5g
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/extras/awslb'
    targetRevision: main
  destination:
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/aws-lb-controller.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awslb-core5g
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: awslb-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://aws.github.io/eks-charts'
    targetRevision: 1.6.2
    chart: aws-load-balancer-controller
    helm:
      valueFiles:
        - values.yaml
      values: |
        clusterName: core5g
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/cert-manager.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: cert-manager-sde-core5g
  name: cert-manager-core5g
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.13.3
    chart: cert-manager
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/external-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-core5g
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: external-secrets-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.13
    chart: 'external-secrets'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        null
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/longhorn.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-core5g
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.6.0
    chart: 'longhorn'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          enabled: false
          host: longhorn-core5g.tactile5g.int
          ingressClassName: nginx
        preUpgradeChecker:
          jobEnabled: false
          upgradeVersionCheck: false
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-core5g
#  name: metallb-adh-core5g
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb/'
    targetRevision: 0.13.12
    chart: 'metallb'
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: ext-metallb-lkh-core5g
  name: ext-metallb-core5g
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/extras/metallb'
    targetRevision: main
  destination:
    namespace: metallb-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metric-server.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server-core5g
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.9.3
    chart: metrics-server
    helm:
      valueFiles:
        - values.yaml
      values: |
        apiService:
          create: true
        extraArgs:
          - --kubelet-insecure-tls=true
          - --kubelet-preferred-address-types=InternalIP

  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/prometheus.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-core5g
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/monitoring/prometheus'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        null
  destination:
    namespace: prometheus-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/skooner.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skooner-core5g
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/monitoring/skooner'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        null
  destination:
    namespace: skooner-system
    server: https://internal-edge-clusters-core5g-apiserver-988246090.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
