apiVersion: v2
name: Helm monitoring stack
description: A Helm chart for Kubernetes monitoring stack
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: grafana
    version: "*"
  - name: prometheus
    version: "*"
  - name: skooner
    version: "*"
  - name: metrics-server
    repository: 'https://charts.bitnami.com/bitnami'
    version: 6.9.3