
grafana:
  enabled: true
  env:
    prometheusUrl: http://prometheus.monitoring.svc.cluster.local:9090
  ingress:
    enable: true
    hosts:
      - host: grafana-dt.tactile5g.int
        paths:
          - path: /
            pathType: Prefix

prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: prometheus-dt.tactile5g.int
        paths:
          - path: /
            pathType: Prefix
  serviceAccount:
    create: false

skooner:
  enabled: true
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: skooner.tactile5g.com
        paths:
          - path: /
            pathType: Prefix

metrics-server:
  enabled: false
  apiService:
    create: true
  extraArgs:
    - --kubelet-insecure-tls=true
    - --kubelet-preferred-address-types=InternalIP
