---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  source:
    repoURL: 'https://charts.helm.sh/stable'
    targetRevision: HEAD
    chart: nginx
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx
  project: clusters
  syncPolicy:
    automated: {}
    #      prune: true
    #      allowEmpty: true
    #      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
#      - PruneLast=true
#      - PrunePropagationPolicy=background
