---
# Source: edge-clusters/templates/capi-template-outpost.yaml
# this file install infra in aws (sgs, route-table, ec2, lb)
# install 1 master (control plane), 1 node (worker) using an existent infra (vcp, igw, natgtw)
# https://blog.scottlowe.org/2019/09/09/consuming-preexisting-aws-infrastructure-with-cluster-api/
# https://techbloc.net/archives/4661

apiVersion: v1
kind: Namespace
metadata:
  name: edge-clusters-example-in-edge-1
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: edge-clusters-example-in-edge-1
  namespace: edge-clusters-example-in-edge-1
spec:
  region: eu-west-3
  additionalTags:
    enviroment: edge
  sshKeyName: tactile5g
  controlPlaneLoadBalancer:
    scheme: internal
    subnets:
      - subnet-0402e76036448a797 # private subnet region
      - subnet-0f75715e78d6e26b2 # private subnet region
      - subnet-07820fd9a7e2693e8 # private subnet region
  bastion:
    enabled: false
  network:
    vpc:
      id: vpc-08291124993d8220b
    subnets:
      - id: subnet-01b49d44875bfb66d  # private subnet outpost
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: edge-clusters-example-in-edge-1-control-plane
  namespace: edge-clusters-example-in-edge-1
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: c6id.2xlarge
      sshKeyName: tactile5g
      rootVolume:
        size: 80
      additionalSecurityGroups:
        - name: "edge-clusters-example-in-edge-1-sgs"
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: edge-clusters-example-in-edge-1-worker
  namespace: edge-clusters-example-in-edge-1
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: c6id.2xlarge
      sshKeyName: tactile5g
      rootVolume:
        size: 80
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: edge-clusters-example-in-edge-1
  namespace: edge-clusters-example-in-edge-1
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: edge-clusters-example-in-edge-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: edge-clusters-example-in-edge-1
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: edge-clusters-example-in-edge-1-worker
  namespace: edge-clusters-example-in-edge-1
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}'
      preKubeadmCommands:
        - |
          sudo echo "
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens6:
                dhcp4: true
                dhcp4-overrides:
                  use-routes: false
                routes:
                  - to: 10.11.0.0/16
                    via: 10.11.29.1
                  - to: 10.182.32.0/24
                    via: 10.11.29.1
          " | sudo tee -a /etc/netplan/ens6.yaml
      postKubeadmCommands:
        - netplan apply && ip link set ens6 up
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane 
metadata:
  name: edge-clusters-example-in-edge-1-control-plane
  namespace: edge-clusters-example-in-edge-1
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: edge-clusters-example-in-edge-1-control-plane
  replicas: 1
  version: v1.25.0
---
# Source: edge-clusters/templates/capi-template-outpost.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: edge-clusters-example-in-edge-1-worker
  namespace: edge-clusters-example-in-edge-1
spec:
  clusterName: edge-clusters-example-in-edge-1
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: edge-clusters-example-in-edge-1-worker
      clusterName: edge-clusters-example-in-edge-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: edge-clusters-example-in-edge-1-worker
      version: v1.25.0
