---
# Source: Helm cluster addons/templates/cert-manager.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: cert-manager-cxn-opentwins
  name: cert-manager-opentwins
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.13.3
    chart: cert-manager
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/external-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-opentwins
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: external-secrets-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.13
    chart: 'external-secrets'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        installCRDs: true
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/grafana.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-opentwins
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/monitoring/grafana'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          annotations: null
          className: nginx
          enabled: false
          environment: edge
        service:
          type: LoadBalancer
  destination:
    namespace: grafana-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/ingress-nginx.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ing-opentwins
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ingress-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.9.0
    chart: 'ingress-nginx'
    helm:
      valueFiles:
        - values.yaml
      values: |
        rbac:
          create: true
        controller:
          service:
            type: NodePort
          extraArgs:
            enable-ssl-passthrough: "true"
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/longhorn.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-opentwins
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.6.0
    chart: 'longhorn'
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          enabled: false
          host: longhorn-opentwins.tactile5g.int
          ingressClassName: nginx
        preUpgradeChecker:
          jobEnabled: false
          upgradeVersionCheck: false
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-opentwins
#  name: metallb-bgc-opentwins
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb/'
    targetRevision: 0.13.12
    chart: 'metallb'
  sources: []
  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
#  name: ext-metallb-slr-opentwins
  name: ext-metallb-opentwins
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/extras/metallb'
    targetRevision: main
  destination:
    namespace: metallb-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/metric-server.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server-opentwins
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.9.3
    chart: metrics-server
    helm:
      valueFiles:
        - values.yaml
      values: |
        apiService:
          create: true
        extraArgs:
          - --kubelet-insecure-tls=true
          - --kubelet-preferred-address-types=InternalIP

  project: addons
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/prometheus.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-opentwins
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/monitoring/prometheus'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          className: nginx
          enabled: false
          environment: edge
        service:
          type: NodePort
  destination:
    namespace: prometheus-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
---
# Source: Helm cluster addons/templates/skooner.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skooner-opentwins
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: 'https://github.com/5gplustactile/auto-ztp.git'
    path: 'templates/cluster-addons/monitoring/skooner'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        
        ingress:
          className: nginx
          enabled: false
          environment: edge
        service:
          type: NodePort
  destination:
    namespace: skooner-system
    server: https://internal-kx7x60bjvby2tvc0r53vvci12514-k8s-663204783.eu-west-3.elb.amazonaws.com:6443
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=background
