---
# helm module not available using ansible 2.9. Ansible 8 version still not released

- name: aws load balancer controller
  block:
    - name: Add helm repo
      command: helm repo add eks https://aws.github.io/eks-charts
      
    - name: Apply the configuration using kubectl
      command: |
        kubectl apply -f {{ main_path }}/tactile5g-local-auto-ztp/ansible/rke2-install/required/crds.yaml --kubeconfig {{ main_path }}/to-delete/rke2.yaml

    - name: Update helm repo
      command: helm repo update

    - name: Install aws load balancer controller
      command: >
        helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system 
        --set clusterName={{ name_cluster }} --set nodeSelector.cluster={{ name_cluster }}
        --kubeconfig {{ main_path }}/to-delete/rke2.yaml
  when: "{{ aws_lb_controller.enable }} == true"