---
# helm module not available using ansible 2.9. Ansible 8 version still not released

- name: cert-manager
  block:
    - name: Add helm repo
      command: helm repo add jetstack https://charts.jetstack.io

    - name: Update helm repo
      command: helm repo update

    - name: Install cert-manager
      command: >
        helm upgrade --install cert-manager jetstack/cert-manager
        --namespace cert-manager
        --create-namespace
        --version v1.12.0
        --set installCRDs=true
        --set installCRDs=true 
        --kubeconfig {{ main_path }}/to-delete/rke2.yaml
  when: "{{ cert_manager.enable }} == true"
